version: 1.0.{build}
image: Visual Studio 2015
configuration: Release
platform: Any CPU
environment:
  COVERALLS_REPO_TOKEN:
    secure: VyyiHIJv/p8KuVZ+2RWsU/NqCHxNM7hcLupLOzhtKf0gRygNzr7ZInC28MQjs/fA
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: $(assembly_version)
  assembly_file_version: $(assembly_version)
  assembly_informational_version: $(assembly_informational_version)
install:
- cmd: git submodule update --init --recursive
- ps: >-
    dotnet --info
before_build:
- ps: >-
    dotnet restore
build:
  project: Stubble.sln
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
test_script:
- ps: >-
    $Package_Locations = ".\packages";
    $OpenCover_Location = Get-ChildItem ($Package_Locations + "\OpenCover*\tools") | Select-Object -First 1 -ExpandProperty FullName;
    $Xunit_Location = Get-ChildItem ($Package_Locations + "\xunit.runner.console*\tools") | Select-Object -First 1 -ExpandProperty FullName;
    $CoverallsNet_Location = Get-ChildItem ($Package_Locations + "\coveralls.net*") | Select-Object -First 1 -ExpandProperty FullName;

    $openCoverExe = "$OpenCover_Location\OpenCover.Console.exe -register:user -target:""$Xunit_Location\xunit.console.exe"" ""-targetargs:"""".\Stubble.Core.Tests\bin\$env:CONFIGURATION\Stubble.Core.Tests.dll"""" -noshadow -appveyor"" -filter:""+[Stubble.*]*"" -skipautoprops -output:coverage.xml";
    $coverallsExe = "$CoverallsNet_Location\csmacnz.Coveralls.exe --opencover -i coverage.xml --repoToken $env:COVERALLS_REPO_TOKEN --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage ""$env:APPVEYOR_REPO_COMMIT_MESSAGE"" --jobId $env:APPVEYOR_JOB_ID"

    iex $openCoverExe;
    iex $coverallsExe;
artifacts:
- path: Stubble\bin\$(Configuration)\Stubble.Core.dll
deploy:
- provider: NuGet
  api_key:
    secure: EMoHTW3rc1OUCEnrICn6gxCbaT8a3HSkedN6mbHqOzo1KHQodR13frz6FZwQuweE
  on:
    APPVEYOR_REPO_TAG: true
